# Generated by Django 3.1.4 on 2021-01-04 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('article_time', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('title', models.CharField(max_length=255)),
                ('article_content', models.CharField(max_length=4000)),
                ('article_img1', models.ImageField(blank=True, null=True, upload_to='cag')),
                ('article_img2', models.ImageField(blank=True, null=True, upload_to='cag')),
                ('article_img3', models.ImageField(blank=True, null=True, upload_to='cag')),
                ('article_img4', models.ImageField(blank=True, null=True, upload_to='cag')),
                ('article_img5', models.ImageField(blank=True, null=True, upload_to='cag')),
                ('article_img6', models.ImageField(blank=True, null=True, upload_to='cag')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person')),
            ],
        ),
    ]
