# Generated by Django 3.1.4 on 2021-01-04 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20210104_1623'),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='a_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='文章ID'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_content',
            field=models.CharField(max_length=4000, verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, verbose_name='发表时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='作者ID'),
        ),
    ]
