# Generated by Django 3.1.4 on 2021-01-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210104_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章管理'},
        ),
        migrations.AlterField(
            model_name='article',
            name='article_content',
            field=models.TextField(blank=True, null=True, verbose_name='文章内容'),
        ),
    ]
