# Generated by Django 3.1.4 on 2021-01-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20210105_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_img1',
            field=models.ImageField(blank=True, null=True, upload_to='art'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_img2',
            field=models.ImageField(blank=True, null=True, upload_to='art'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_img3',
            field=models.ImageField(blank=True, null=True, upload_to='art'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_img4',
            field=models.ImageField(blank=True, null=True, upload_to='art'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_img5',
            field=models.ImageField(blank=True, null=True, upload_to='art'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_img6',
            field=models.ImageField(blank=True, null=True, upload_to='art'),
        ),
    ]
