# Generated by Django 3.1.4 on 2021-01-07 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0010_auto_20210107_2101'),
        ('article', '0005_auto_20210105_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='update_time1',
            field=models.DateTimeField(default='', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='作者'),
        ),
    ]
