# Generated by Django 3.1.4 on 2021-01-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='注册时间')),
                ('nickname', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20, verbose_name='真实姓名')),
                ('sex', models.IntegerField(choices=[(0, '男'), (1, '女')], default=0)),
                ('height', models.FloatField(default=170, help_text='cm')),
                ('location', models.CharField(max_length=255)),
                ('hometown', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=20)),
                ('college', models.CharField(max_length=255, verbose_name='毕业院校')),
                ('job', models.CharField(max_length=50)),
                ('income', models.IntegerField(default=6000)),
                ('estate', models.CharField(max_length=255)),
                ('heart', models.IntegerField(default=0)),
            ],
        ),
    ]
