# Generated by Django 3.1.4 on 2021-01-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='education',
            field=models.CharField(max_length=20, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='person',
            name='estate',
            field=models.CharField(max_length=255, verbose_name='房产状况'),
        ),
        migrations.AlterField(
            model_name='person',
            name='heart',
            field=models.IntegerField(default=0, verbose_name='倾心指数'),
        ),
        migrations.AlterField(
            model_name='person',
            name='height',
            field=models.FloatField(default=170, help_text='cm', verbose_name='身高'),
        ),
        migrations.AlterField(
            model_name='person',
            name='hometown',
            field=models.CharField(max_length=255, verbose_name='家乡'),
        ),
        migrations.AlterField(
            model_name='person',
            name='income',
            field=models.IntegerField(default=6000, verbose_name='月收入'),
        ),
        migrations.AlterField(
            model_name='person',
            name='job',
            field=models.CharField(max_length=50, verbose_name='职业'),
        ),
        migrations.AlterField(
            model_name='person',
            name='location',
            field=models.CharField(max_length=255, verbose_name='现居地'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nickname',
            field=models.CharField(max_length=20, verbose_name='用户昵称'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.IntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='person',
            name='uid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID'),
        ),
    ]
