# Generated by Django 3.1.4 on 2021-01-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20210104_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户管理'},
        ),
        migrations.AddField(
            model_name='person',
            name='marriage',
            field=models.CharField(choices=[(0, ''), (1, '未婚'), (2, '离异'), (3, '丧偶')], default=0, max_length=20, verbose_name='婚姻状况'),
        ),
        migrations.AlterField(
            model_name='person',
            name='education',
            field=models.CharField(choices=[(0, ''), (1, '大专以下'), (2, '大专'), (3, '本科'), (4, '硕士及以上')], default=0, max_length=20, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='person',
            name='estate',
            field=models.CharField(choices=[(0, ''), (1, '已购房'), (2, '和父母同居'), (3, '租房'), (4, '其他')], default=0, max_length=20, verbose_name='房产状况'),
        ),
    ]
