# Generated by Django 3.1.4 on 2021-01-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_person_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='income',
            field=models.IntegerField(verbose_name='月收入'),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile', verbose_name='头像'),
        ),
    ]
