# Generated by Django 3.1.4 on 2021-01-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_auto_20210105_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='telephone',
            field=models.CharField(default='', help_text='18位数字', max_length=20, verbose_name='手机号'),
        ),
    ]
