# Generated by Django 3.1.4 on 2021-01-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_person_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birthday',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='生日'),
        ),
    ]
