# Generated by Django 3.1.4 on 2021-01-04 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20210104_1623'),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='a_content',
            field=models.CharField(max_length=500, verbose_name='文字内容'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='a_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='动态时间'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='aid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='动态ID'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='用户ID'),
        ),
    ]
