# Generated by Django 3.1.4 on 2021-01-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20210104_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='a_content',
            field=models.TextField(blank=True, null=True, verbose_name='文字内容'),
        ),
    ]
