# Generated by Django 3.1.4 on 2021-01-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20210104_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': '动态', 'verbose_name_plural': '动态管理'},
        ),
    ]
