# Generated by Django 3.1.4 on 2021-01-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20210105_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='act'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='act'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='act'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='act'),
        ),
    ]
