# Generated by Django 3.1.4 on 2021-01-06 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_auto_20210106_1135'),
        ('activity', '0005_auto_20210105_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='nickname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='act_user', to='person.person', verbose_name='用户昵称'),
        ),
    ]
