# Generated by Django 3.1.4 on 2021-01-07 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0010_auto_20210107_2101'),
        ('activity', '0006_activity_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='update_time',
            field=models.DateTimeField(default='', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='nickname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ac_user', to='person.person', verbose_name='用户昵称'),
        ),
    ]
