# Generated by Django 3.1.4 on 2021-01-04 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('match_time', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, '初识'), (1, '牵手'), (2, '失恋')], default=0)),
                ('a_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_user', to='person.person')),
                ('b_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b_user', to='person.person')),
            ],
        ),
    ]
