# Generated by Django 3.1.4 on 2021-01-04 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20210104_1623'),
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='a_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_user', to='person.person', verbose_name='对象A的ID'),
        ),
        migrations.AlterField(
            model_name='match',
            name='b_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b_user', to='person.person', verbose_name='对象B的ID'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='匹配ID'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_time',
            field=models.DateField(auto_now_add=True, verbose_name='匹配时间'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.IntegerField(choices=[(0, '初识'), (1, '牵手'), (2, '失恋')], default=0, verbose_name='恋爱状态'),
        ),
    ]
