# Generated by Django 3.1.4 on 2021-01-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_auto_20210104_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': '匹配', 'verbose_name_plural': '匹配管理'},
        ),
    ]
