# Generated by Django 3.1.4 on 2021-01-07 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_auto_20210107_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='update_time2',
            field=models.DateField(default=datetime.date(2021, 1, 7), verbose_name='变化时间'),
        ),
    ]
